### ISSUE TITLE
Comparison with mediawiki-bootstrap

### ISSUE THREAD

**Issue by vid** [OSAS/strapping-mediawiki#10]
Just wondering if you could compare & contrast strapping-mediawiki with https://github.com/mtyeh411/mediawiki-bootstrap/issues

I think it's fantastic that these projects exists, but am worried about a dilution of effort and end result.

The SMW support in mediawiki-booststrap is important to me, since strapping doesn't mention it I'd go with it, but strapping's support for bootstrap styles in wiki pages is interesting.

**Comment by garrett** [comment]
I believe that mediawiki-bootstrap is similar but has a different focus.

One of the goals for Strapping is to enable a site to be wiki-powered without looking like a wiki (although it is possible to appear wiki-like too, naturally).

Strapping also tries to use existing MediaWiki conventions, too, such as using `MediaWiki:Sidebar` instead of `Bootstrap:Footer` for navigation, so migrating existing wikis is easier and allowing a user to switch to a custom style would preserve navigation.

While one may use the Strapping skin without layering any additional style on top, it is intended to be a starting point to quickly build up a custom look and feel for a site. I'm not sure if mediawiki-bootstrap has that in mind (although, I'm sure it would certainly be possible through CSS and perhaps some PHP modifications).

When I was originally looking for solutions for setting up [oVirt](http://ovirt.org/), I considered existing Bootstrap-based skins for MediaWiki, and they were either incomplete, did not work, or appeared abandoned. As a goal was to have a site with all parts of MediaWiki skinned, it made sense to start a new one (after a few false starts trying to work with the other skins).

As Strapping was started as a fork of the latest version of Vector, as opposed to being written from scratch, anything that Vector (the default theme of MediaWiki) supports, Strapping should support too. Therefore, it's quite likely that Strapping may even support SMW without any extra effort.

**Comment by garrett** [comment]
(BTW: Sorry for the delayed response. I caught the flu when attending FOSDEM and it took me a while to get over it and catch up with work. :wink:)

**Comment by vid** [comment]
no problem and thanks for your response.

is Strapping tested and designed to work with Semantic Mediawiki? A lot of people use it, and it's one thing mediawiki-bootstrap specifically supports.
