### ISSUE TITLE
No "Create this page" available

### ISSUE THREAD

**Issue by danielwiklund** [OSAS/strapping-mediawiki#26]
I can't find anywhere to create a new wiki page. In the default theme, when you search for something, if not available in the database you get the option to create it. Now I can't find anywhere to create a new wiki page.

(Sorry this is not related to the above. I just must thank you for a great theme and for all the effort you've put into this. Thanks!)

**Comment by garrett** [comment]
There's a "create" button at the top of the page. (It's the second thing on the page — usually as "edit", unless the page doesn't exist yet.)

The toolbar at the top isn't visible enough by default; perhaps this issue is a result of that (and the fact that the skin looks and acts a bit different from most other MediaWiki skins).

**Comment by garrett** [comment]
Fixed the create page link in the empty search results. Thanks for reporting this issue.

I'll open up a new bug about the navigation not being visible enough.

**Comment by danielwiklund** [comment]
Thank you!

**Comment by garrett** [comment]
FWIW: I've opened issue #33 for making the topbar (and the edit/create button) more obvious by default.
