### ISSUE TITLE
CSS issue - Elements are not centered

### ISSUE THREAD

**Issue by clintongreen** [OSAS/strapping-mediawiki#27]
I have tried with 2 fresh installs but I still find that everything is off-centered. I managed to fix it by adding .row,[class*="span"]{ margin-left: 0;} to theme.css. This then affected the offset class so I needed to add them in theme.css too. Is this a bug or am I missing something? I've attached a screenshot that shows the elements off-center. I added a border on everything for this screen shot. Thanks for skin :)

![image](https://f.cloud.github.com/assets/1114866/515683/9fcf3fa6-be80-11e2-9c2f-1135ba7141dd.png)

**Comment by garrett** [comment]
I believe this resulted from a previous update to the skin where a &lt;div&gt; was replaced with a &lt;ul&gt; and &lt;li&gt;, and those brought along their own margin.

(The outlines on the left are intentional, as that's how CSS grids usually work. It's basically the header that's shifted out of place.) 

I have a fix and will be applying it soon.

**Comment by clintongreen** [comment]
Thanks Garrett. I'll check for the next release. Cheers

**Comment by garrett** [comment]
Oh, I was actually thinking of something else for the explanation.

I'm about to submit a _really simple_ CSS change that should fix this. Please let me know if it works for you.
