### ISSUE TITLE
Dropdowns not working

### ISSUE THREAD

**Issue by chrisrouse** [OSAS/strapping-mediawiki#39]
I just installed MediaWiki a couple weeks ago, and just installed Strapping tonight. I also pulled the latest version of Bootstrap (full download). Drop downs are not working for me.

The menus for Page, Action, Toolbox don't dropdown. I know there is content there since it's listed in the Vector theme. I have toggled true/false on the settings in strapping.php, but that did not fix the dropdowns.

**Comment by garrett** [comment]
Odd. They're working here, on multiple sites. 

## Resource-related? (JS/CSS)

Since the theme is Bootstrap-based, it relies on JavaScript. Perhaps the JavaScript isn't loading on your site? (Or you might have it turned off, with something like NoScript?) 

Firebug, Firefox's dev console, and Chrome's web inspector all allow you to see if resources are loading. Is there anything that is having problems loading? (JavaScript and/or CSS)

## PHP problems?

Alternatively: A while back, there was a bug in Strapping's PHP that caused _some_ sites to not render properly (issue #7). Could you turn on debugging and/or check your server's error logs to see if there's a PHP error in the Strapping theme? 

BTW: One method of turning on debugging is adding the following line in your `LocalSettings.php` file:

``` php
$wgShowExceptionDetails = true;
```

## Screenshot?

Also: For the sake of completeness, could you also upload a screenshot here so I can make sure everything else looks correct? (It could _possibly_ be a CSS-related issue, for example… or something else that might be show itself when seen.)

## Thanks for the feedback!

Hopefully we can figure this out soon and get the theme working for you.

**Comment by garrett** [comment]
(Oops; Didn't mean to close the bug.)

**Comment by kamerunkg** [comment]
Hi Garrett, first of all - great theme, thank You for all your work :)

I have the same problem - my buttons don't do dropdowns. I'v found this in Chrome console - 
![zrzut ekranu 2013-08-3 o 14 43 50](https://f.cloud.github.com/assets/5154594/905588/6a441ddc-fc3a-11e2-8c3a-33e4a2ec99fa.png)

And here is a screenshot of webpage, sill raw.

![zrzut ekranu 2013-08-3 o 14 45 15](https://f.cloud.github.com/assets/5154594/905591/9a4587f0-fc3a-11e2-83a4-2d56a7bac822.png)

I would very appreciate your help. Thanks!

**Comment by garrett** [comment]
It looks like somehow your version of jQuery is way out of date. Bootstrap uses $().on(), added in jQuery 1.7:

http://api.jquery.com/on/

What version of MediaWiki are you using?

**Comment by kamerunkg** [comment]
I've checked and its MediaWiki 1.18.

**Comment by garrett** [comment]
As Bootstrap doesn't support jQuery < 1.7 and MediaWiki 1.18.0 was before jQuery 1.7 (or above) was used, please upgrade MediaWiki to use the Strapping theme.

You really should upgrade MediaWiki anyway, as the 1.18.x branch has been discontinued and has security issues. 

(Note: jQuery 1.7 was included in MediaWiki release 1.18.1 and higher.)

**Comment by kamerunkg** [comment]
Thanks Garrett - it worked :)

**Comment by garrett** [comment]
Awesome.

I'm going to assume that this was the problem with the initial bug report too and close this bug. If that's not the case, and this still is an issue with MediaWiki 1.18.1+, then please feel free to re-open and I'll try to figure it out if it is indeed something else.

Also, I have updated the README to list MediaWiki 1.18.1+ as a requirement (and exactly why it is the case).

I'm glad we figured it out and have it working for you!

**Comment by joaobarcia** [comment]
Hi,

First of all, thanks for the great extension! 

I just wanted to mention another possible reason for this issue. The symptoms were exactly the same. However, it was being caused by javascript errors due to the free server were I was hosting my wikimedia injecting html code into the load.php. I checked it by using Firebug in Console mode and got a few "SyntaxError: syntax error" in load.php.

As described in: http://www.mediawiki.org/wiki/Manual:Errors_and_symptoms#Missing_edit_toolbar.2C_JavaScript_not_working

Solution: Change server
